server:
  port: 4040

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oauth?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 7ae3022d0bd42bea9ca9
            clientSecret: e2e86db514321ee2407b5f652ba96ebbfc772356
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
    provider:
      github:
        authorization-uri: https://github.com/login/oauth/authorize
        token-uri: https://github.com/login/oauth/access_token
        user-info-uri: https://api.github.com/user